production:
  adapter: mysql2
  database: mgis_prod
  host: localhost
  username: root
  password: admin
  encoding: utf8

development:
  adapter: mysql2
  database: mgis_dev
  host: localhost
  username: root
  password: admin
  encoding: utf8
  pool: 25
